name: Run gperftools Profiling

on:
  workflow_dispatch:
    inputs:
      benchmark1:
        description: 'Benchmark to run'
        required: true
        default: 'TPE_abb20_2step'

jobs:
  build-and-profile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake libtool gperf cmake g++ # Install CMake and build tools
        git clone https://github.com/gperftools/gperftools.git
        cd gperftools
        ./autogen.sh
        ./configure
        make
        sudo make install
        
    - name: Build
      run: |
        mkdir -p build
        cmake -B ${{github.workspace}}/build
        cmake --build ${{github.workspace}}/build

    - name: Run  benchmark with profiling
      run: |
        cd build
        cd benchmarks
        LD_PRELOAD=/usr/local/lib/libprofiler.so CPUPROFILE=benchmark1.prof ./${{ github.event.inputs.benchmark1 }}
        cd ..
        cd ..
    - name: Generate profiling report for benchmark
      run: |
        cd build
        cd benchmarks
        pprof --text ./${{ github.event.inputs.benchmark1 }} benchmark1.prof > benchmark1_profile.txt
        pprof --pdf ./${{ github.event.inputs.benchmark1 }} benchmark1.prof > benchmark1_profile.pdf
        cd ..
        cd ..

    - name: Upload profiling reports
      uses: actions/upload-artifact@v3
      with:
        name: profiling-reports
        run: |
          cd build
          cd benchmarks
        path: |
          benchmark1_profile.txt
          benchmark1_profile.pdf


